server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:h2:mem:memDb
    user: sa
    password:
    driverClassName: org.h2.Driver